### ISSUE TITLE
BarCode 93 not printing

### ISSUE THREAD

**Issue by pedrollanes** [lukevp/ESC-POS-.NET#100]
Two issues: In barcode 93 I'm trying to print this code $EC0MNRN1V7G$. If I put in this value I recieve a exception that Code39 requires * at start and end, but I'm trying to use code 93. 
Second issue: I put * for avoiding this error and I have not any error but printer doesn't print the barcode.

Thanks

**Comment by igorocampos** [comment]
About the error message, it is clearly a misspelling where the correct message should say `Code93` instead of `Code39`, at least I've never heard of a Code39 type of barcode. And you can check the source code that originated the message:
![image](https://user-images.githubusercontent.com/10572656/103580453-fc5f8700-4eb8-11eb-997c-4bf08216ab90.png)

About the printer not printing anything, you will have to check if it is compatible with Code93 type of barcode. Which printer and model are you using? And is there any specific reason why use Code39, instead of Code128 for example?

**Comment by pedrollanes** [comment]
At last the problem is that the width exceed the paper width. I have used code128 and work fine. Thanks

**Comment by lukevp** [comment]
Thanks @pedrollanes for calling out the typo in the exception, this has been fixed in the prerelease version of the library and this issue is closed.  I'm glad you got the barcode to print correctly!
