### ISSUE TITLE
QRCode help

### ISSUE THREAD

**Issue by Dufayel** [lukevp/ESC-POS-.NET#119]
Hi, is there any way to print a qrcode with right text? like that image bellow?
![image](https://user-images.githubusercontent.com/11709293/129237904-d196f6a6-4269-41db-ac08-87535baa56e6.png)

**Comment by igorocampos** [comment]
Hello there, I believe the only way to accomplish that is using the PAGE MODE. Unfortunately I don't think it has been implemented in this library. But you are very welcome to contribute :) 

![image](https://user-images.githubusercontent.com/10572656/132004225-1bcf7296-ac4b-4034-8f08-4b814eb0a81d.png)


Since you are brazilian, [here](https://www.projetoacbr.com.br/forum/topic/43887-qrcode-e-logotipo-lateral-em-danfce-escpos/) is a forum that had it implemented in their open source solution. You can easily check their source code for the necessary commands and implement through a PR in this project.

Below a list of commands that would more likely to be implemented:
- `ESC L` -   Select page mode 
- `ESC FF`  - Print data in page mode 
- `ESC T` -  Select print direction in page mode
- `GS $` -  Set absolute vertical print position in page mode 
- `GS  ＼`-  Set relative vertical print position in page mode
- `ESC W` -  Set printing area in page mode

**Comment by Dufayel** [comment]
Thank you very much! it's saved my life.
