### ISSUE TITLE
Print pdf file

### ISSUE THREAD

**Issue by juliogamasso** [lukevp/ESC-POS-.NET#13]
Hello @lukevp, did you get to read something about PDF printing using ESC POS? I could not figure out how to do it using the commands. Thank you!

**Comment by montyclt** [comment]
Maybe transforming the PDF file into bitmap image and print it with image commands?

**Comment by juliogamasso** [comment]
I also thought about this, but it is very difficult to convert pdf into image

**Comment by lukevp** [comment]
@juliogamasso there's nothing in the ESCPOS standard that would let you print a PDF, you would have to use a separate library to rasterize it before printing.  What sort of PDF do you have that would be printable on a receipt printer?  Perhaps you could get the data in a different format?

**Comment by juliogamasso** [comment]
The receipts can come in the format of the attached image, would it be possible to align a QrCode the way it is in the image? I have already implemented but only line by line, not side as it is in the image. If it is possible to mount an equal receipt using the commands we have already solved the problem.
![danfe nfce](https://user-images.githubusercontent.com/43079921/58880808-2a626100-86af-11e9-85ab-71e51f21ccdb.png)

**Comment by lukevp** [comment]
To do this natively in ESCPOS, I believe this is something you would have
to use Page Mode for, which is not currently supported in the library. Page
Mode lets you control the printing position and place elements next to each
other. We don't need that for receipt prints since the area is so narrow,
so I haven't implemented Page Mode and don't plan on adding it, but it is
something you could add. Or you can try converting the PDF to a PNG and
printing that way.

**Comment by juliogamasso** [comment]
Allright thanks.
