### ISSUE TITLE
is it supported for older .net version?

### ISSUE THREAD

**Issue by fgroupindonesia** [lukevp/ESC-POS-.NET#55]
i searched through out some docs and found out that it's only for .NET 4.7.2 is that true?

What about the older version of .NET do you support it as well?
Here we're still using 3.5, 4.0, and 4.5 .NET version.

regards,

**Comment by lukevp** [comment]
Hey @fgroupindonesia the reason it is for 4.7.2 and newer is because it is a .net standard 2.0 library and it depends on a couple .net core things.  However, most of the code should work back to 4.0/4.5 if you want to check out the app yourself and change it to a 4.5 class library and build it.  The code is MIT licensed so you are welcome to fork it and use it for commercial purposes, you just must maintain the license that is attached.
